; PlatformIO Project Configuration File

; Develop for ESP32 DOIT DevKit V1 using Arduino framework
[env:esp32doit-devkit-v1]

; Platform configuration
platform = espressif32

; Board configuration
board = esp32doit-devkit-v1

; Framework configuration
framework = arduino

; Monitor configuration
monitor_speed = 115200

; Library dependencies
lib_deps = knolleary/PubSubClient @ ^2.8